debug_mode: false
map_perlin_seed: 0123012301230123
biome_scaling: 512
region_scaling: 1024
horizontal_scaling: 32
vertical_scaling: 8
threshold: 0.3
water_level: 42

regions:
  hot:
    weight: 32
    biomes:
      desert:
        weight: 15
        fill_block: SANDSTONE
        surface_block: SAND
        structures:
          cactus0:
            weight: 5
            blocks:
              0=1=0: CACTUS
              -1=1=0: AIR
              1=1=0: AIR
              0=1=-1: AIR
              0=1=1: AIR
              0=2=0: CACTUS
              -1=2=0: AIR
              1=2=0: AIR
              0=2=-1: AIR
              0=2=1: AIR
              0=3=0: CACTUS
              -1=3=0: AIR
              1=3=0: AIR
              0=3=-1: AIR
              0=3=1: AIR
          cactus1:
            weight: 5
            blocks:
              0=1=0: CACTUS
              -1=1=0: AIR
              1=1=0: AIR
              0=1=-1: AIR
              0=1=1: AIR
              0=2=0: CACTUS
              -1=2=0: AIR
              1=2=0: AIR
              0=2=-1: AIR
              0=2=1: AIR
          cactus2:
            weight: 5
            blocks:
              0=1=0: CACTUS
              -1=1=0: AIR
              1=1=0: AIR
              0=1=-1: AIR
              0=1=1: AIR
          dead_bush:
            weight: 15
            blocks:
              0=1=0: DEAD_BUSH
          void:
            weight: 240
            blocks:
              0=1=0: AIR
  temparate:
    weight: 64
    biomes:
      green:
        weight: 40
        fill_block: DIRT
        surface_block: GRASS_BLOCK
        structures:
          tree:
            weight: 40
            blocks:
              0=1=0: OAK_LOG
              -1=1=0: OAK_LEAVES
              1=1=0: OAK_LEAVES
              0=1=-1: OAK_LEAVES
              0=1=1: OAK_LEAVES
              0=2=0: OAK_LEAVES
          grass:
            weight: 40
            blocks:
              0=1=0: GRASS
          tall_grass:
            weight: 40
            blocks:
              0=1=0: TALL_GRASS
          void:
            weight: 480
            blocks:
              0=1=0: AIR
  cold:
    weight: 32
    biomes:
      ice:
        weight: 40
        fill_block: ICE
        surface_block: SNOW_BLOCK
        structures:
          rock:
            weight: 40
            blocks:
              0=1=0: STONE
              -1=1=0: STONE
              1=1=0: STONE
              0=1=-1: STONE
              0=1=1: STONE
              0=2=0: STONE
          void:
            weight: 512
            blocks:
              0=1=0: AIR
  special:
    weight: 4
    biomes:
      mushroom:
        weight: 40
        fill_block: DIRT
        surface_block: MYCELIUM
        structures:
          brown_mushroom:
            weight: 40
            blocks:
              0=1=0: BROWN_MUSHROOM
          red_mushroom:
            weight: 40
            blocks:
              0=1=0: RED_MUSHROOM
          void:
            weight: 512
            blocks:
              0=1=0: AIR
